server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:backend
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect